
<div class="container footer-block">
        <div class="row footer-nav-group">
					<div class="col-md-3 footer-nav-block">
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_info_block')->toHtml() ?>
					</div>
					<div class="col-md-3 footer-nav-block">
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_sale_block')->toHtml() ?>
					</div>
					<div class="col-md-3 footer-nav-block">
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_user_block')->toHtml() ?>
					</div>
					<div class="col-md-3 footer-nav-block">
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_links_sm')->toHtml() ?>
					</div>
				</div>
        <address class="copyright"><?php echo $this->getCopyright() ?></address>
</div>
