<?php if ($_products = $this->getRecentlyViewedProducts()): ?>
<div class="block block-list block-viewed">
    <div class="block-title">
        <h4 class="compare-products-title"><?php echo $this->__('Compare Products') ?></h4>
		<p class="compare-products-text"><?php echo $this->__('You have no items to compare.') ?></p>
    </div>
    <div class="block-content">

        <script type="text/javascript">decorateList('recently-viewed-items');</script>
    </div>
</div>
<?php endif; ?>
