<?php
$testimonials = $this->getTestimonialsCollection();
$testimonialsViewUrl = Mage::getUrl('testimonials/index/view');
$isLoggedIn = Mage::getSingleton('customer/session')->isLoggedIn();
?>

<div class="testimonials-header">
    <h2 class="testimonials-header-title"><?php echo $this->__('Testimonials') ?></h2>
    <button
        <?php
        echo $isLoggedIn
            ? "data-toggle='modal' data-target='#testimonialModal' class='button'"
            : "class='button disabled' title='Please Log In'";
        ?>
    >
        <?php echo $this->__('Submit Your Testimonial') ?>
    </button>
</div>

<?php foreach ($testimonials as $item): ?>
    <div class="content">
        <div class="testimonial">
            <?php echo $item->getContent(); ?>
            <div class="testimonial-arrow"></div>
        </div>
        <span class="user-name">
            <?php echo Mage::getModel('customer/customer')->load($item->getCustomerId())->getName(); ?>
        </span>
    </div>
<?php endforeach; ?>

<!-- Pager Block -->
<?php echo $this->getPagerHtml(); ?>

<!-- Modal Window "New Testimonial"  -->
<?php echo $this->getChildHtml('testimonials_form'); ?>