<form action="<?php echo $this->getUrl('testimonials/index/post'); ?>"
      id="testimonialForm"
      class="testimonialForm"
      method="post"
      enctype="multipart/form-data">
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Testimonial') ?></h2>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="name" class="required"><em>*</em><?php echo $this->__('Name') ?></label>
                    <div class="input-box">
                       <input name="name" id="name"
                       title="<?php echo $this->__('Name') ?>"
                       value="<?php echo $this->escapeHtml($this->getUserName()) ?>" class="input-text required-entry" type="text" />
                    </div>
                </div>
                <div class="field">
                    <label for="email" class="required"><em>*</em><?php echo $this->__('Email') ?></label>
                    <div class="input-box">
                        <input name="email" id="email" title="<?php echo $this->__('Email') ?>" value="<?php echo $this->escapeHtml($this->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />
                    </div>
                </div>
                <?php if (Mage::helper('testimonials')->isCompanyEnabled()): ?>
                    <div class="field">
                        <label for="company"><?php echo $this->__('Company') ?></label>
                        <div class="input-box">
                            <input name="company" id="company" title="<?php echo $this->__('Company') ?>" value="<?php echo $this->escapeHtml($this->getCompany()) ?>" class="input-text" type="text" />
                        </div>
                    </div>
                <?php endif ?>

                <div class="field">
                    <label><?php echo $this->__('Rating') ?></label>
                    <div class="input-box ratings-table">
                    <?php for ($i = 1; $i <= 5; ++$i) { ?>
                        <label for="rating_<?php echo $i; ?>"><?php echo $i; ?>
                            <input type="radio" name="rating" id="rating_<?php echo $i; ?>" value="<?php echo $i; ?>" class="radio" <?php if ($this->checkRating($i)): ?>checked="checked"<?php endif; ?> />
                        </label>
                    <?php } ?>
                    <?php if (Mage::helper('testimonials')->isStarsOnFormEnabled()) : ?>
                        <div id="testimonial-form-rating-box" style="display: none;" class="rating-box"><div id="testimonial-form-rating" class="rating" style="width: 0"></div></div>
                    <?php endif;?>
                    </div>
                </div>
            </li>
            <li <?php if ($this->getLayout()->getBlock('root')
                        ->getTemplate() != "page/3columns.phtml"): ?>class="wide"<?php endif ?>>
                <label for="message" class="required"><em>*</em><?php echo $this->__('Message') ?></label>
                <div class="input-box">
                    <textarea name="message" id="message"
                        title="<?php echo $this->__('Message') ?>"
                        class="required-entry input-text" cols="5" rows="3"><?php echo $this->getUserMessage(); ?></textarea>
                </div>
            </li>
            <?php echo $this->getChildHtml('testimonials.captcha'); ?>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
        <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
        <button class="button" onclick="setLocation('<?php echo $this->getUrl('testimonials'); ?>'); return false;">
            <span><span><?php echo $this->__('Back') ?></span></span>
        </button>
    </div>
</form>
